language: node_js
node_js:
  -  12
  -  10

script:
  - npm test

jobs:
  include:
    - stage: 'npm Release'
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release